#define PJ_DEBUG						0

#define PJ_IOQUEUE_MAX_HANDLES			1024

#define PJSIP_MAX_TRANSPORTS			32
#define PJSIP_MAX_RESOLVED_ADDRESSES	32

#define PJSUA_MAX_ACC					512
#define PJSUA_MAX_CALLS					512
#define PJSUA_MAX_PLAYERS				512
